In [2]:
import pandas as pd

df = pd.read_csv('../data/processed/repositories_001.csv')
df.head()

,owner,name,stars,forks,watchers,languageCount,description,primaryLanguage,createdAt,pushedAt,languages,topics
0,freeCodeCamp,freeCodeCamp,426893,41377,8588,6,freeCodeCamp.org's open-source codebase and cu...,TypeScript,2014-12-24T17:49:19Z,2025-08-31T09:33:14Z,"['TypeScript', 'JavaScript', 'CSS', 'Dockerfil...","['learn-to-code', 'nonprofits', 'programming',..."
1,codecrafters-io,build-your-own-x,415801,38976,6247,1,Master programming by recreating your favorite...,Markdown,2018-05-09T12:03:18Z,2025-08-29T00:08:20Z,['Markdown'],"['programming', 'tutorials', 'tutorial-code', ..."
2,sindresorhus,awesome,396445,31414,8011,0,😎 Awesome lists about all kinds of interesting...,NaN,2014-07-11T13:42:37Z,2025-07-18T18:37:33Z,[],"['awesome', 'awesome-list', 'unicorns', 'lists..."
3,EbookFoundation,free-programming-books,366964,64025,9879,2,:books: Freely available programming books,Python,2013-10-11T06:50:37Z,2025-08-25T21:06:44Z,"['Python', 'HTML']","['education', 'books', 'list', 'resource', 'ha..."
4,public-apis,public-apis,363505,38166,4360,2,A collective list of free APIs,Python,2016-03-20T23:49:42Z,2025-05-20T15:56:34Z,"['Python', 'Shell']","['api', 'public-apis', 'free', 'apis', 'list',..."

In [3]:
df.shape

(50000, 12)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   owner            50000 non-null  str
 1   name             49998 non-null  str
 2   stars            50000 non-null  int64
 3   forks            50000 non-null  int64
 4   watchers         50000 non-null  int64
 5   languageCount    50000 non-null  int64
 6   description      48980 non-null  str
 7   primaryLanguage  45769 non-null  str
 8   createdAt        50000 non-null  str
 9   pushedAt         50000 non-null  str
 10  languages        50000 non-null  str
 11  topics           50000 non-null  str
dtypes: int64(4), str(8)
memory usage: 4.6 MB

In [5]:
(df['languages'] == '[]').sum()

np.int64(4241)

In [6]:
(df['topics'] == '[]').sum()

np.int64(16836)

In [7]:
((df['languages'] == '[]') & (df['topics'] == '[]')).sum()

np.int64(1800)

In [8]:
(
    df['description'].fillna('').str.strip().eq('')
    & df['languages'].eq('[]')
    & df['topics'].eq('[]')
).sum()

np.int64(152)

In [9]:
df['stars'].describe()

count     50000.000000
mean       4719.690480
std       10087.858219
min         876.000000
25%        1508.000000
50%        2261.000000
75%        4300.250000
max      426893.000000
Name: stars, dtype: float64

In [10]:
profile_repos =df[df['owner'].str.lower() == df['name'].str.lower()]

In [11]:
profile_repos.shape

(3859, 12)

In [12]:
import pandas as pd
df = pd.read_csv('../data/processed_v2/repositories_01.csv')
df.head()

,owner,name,stars,forks,watchers,languageCount,description,primaryLanguage,createdAt,pushedAt,languages,topics,isFork,isArchived
0,freeCodeCamp,freeCodeCamp,426893,41377,8588,6,freeCodeCamp.org's open-source codebase and cu...,TypeScript,2014-12-24T17:49:19Z,2025-08-31T09:33:14Z,"['TypeScript', 'JavaScript', 'CSS', 'Dockerfil...","['learn-to-code', 'nonprofits', 'programming',...",False,False
1,codecrafters-io,build-your-own-x,415801,38976,6247,1,Master programming by recreating your favorite...,Markdown,2018-05-09T12:03:18Z,2025-08-29T00:08:20Z,['Markdown'],"['programming', 'tutorials', 'tutorial-code', ...",False,False
2,sindresorhus,awesome,396445,31414,8011,0,😎 Awesome lists about all kinds of interesting...,NaN,2014-07-11T13:42:37Z,2025-07-18T18:37:33Z,[],"['awesome', 'awesome-list', 'unicorns', 'lists...",False,False
3,EbookFoundation,free-programming-books,366964,64025,9879,2,:books: Freely available programming books,Python,2013-10-11T06:50:37Z,2025-08-25T21:06:44Z,"['Python', 'HTML']","['education', 'books', 'list', 'resource', 'ha...",False,False
4,public-apis,public-apis,363505,38166,4360,2,A collective list of free APIs,Python,2016-03-20T23:49:42Z,2025-05-20T15:56:34Z,"['Python', 'Shell']","['api', 'public-apis', 'free', 'apis', 'list',...",False,False

In [13]:
df.shape

(100000, 14)

In [14]:
df['isFork'].value_counts()

isFork
False    100000
Name: count, dtype: int64

In [15]:
df['isArchived'].value_counts()

isArchived
False    92459
True      7541
Name: count, dtype: int64

In [16]:
df['pushedAt'].head()

0    2025-08-31T09:33:14Z
1    2025-08-29T00:08:20Z
2    2025-07-18T18:37:33Z
3    2025-08-25T21:06:44Z
4    2025-05-20T15:56:34Z
Name: pushedAt, dtype: str

In [17]:
df['createdAt'].head()

0    2014-12-24T17:49:19Z
1    2018-05-09T12:03:18Z
2    2014-07-11T13:42:37Z
3    2013-10-11T06:50:37Z
4    2016-03-20T23:49:42Z
Name: createdAt, dtype: str

In [18]:
df['pushedAt'] = pd.to_datetime(df['pushedAt'], utc=True)

In [19]:
df['createdAt'] = pd.to_datetime(df['createdAt'], utc=True)

In [20]:
df['pushedAt'].min()

Timestamp('2010-01-23 23:20:32+0000', tz='UTC')

In [21]:
df['pushedAt'].max()

Timestamp('2025-09-01 09:39:12+0000', tz='UTC')

In [22]:
df['repo_age_days'] = (
    df['pushedAt'] - df['createdAt']
).dt.days

In [23]:
df['createdAt'] = pd.to_datetime(df['createdAt'], utc=True)

In [24]:
df[['createdAt', 'pushedAt']].dtypes

createdAt    datetime64[us, UTC]
pushedAt     datetime64[us, UTC]
dtype: object

In [25]:
(df['repo_age_days'] < 0).sum()

np.int64(18)

In [26]:
df = df[df['repo_age_days'] >= 0]

In [27]:
reference_date = df['pushedAt'].max()

In [28]:
reference_date

Timestamp('2025-09-01 09:39:12+0000', tz='UTC')

In [42]:
df.info()

<class 'pandas.DataFrame'>
Index: 99951 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   owner            99951 non-null  str
 1   name             99949 non-null  str
 2   stars            99951 non-null  int64
 3   forks            99951 non-null  int64
 4   watchers         99951 non-null  int64
 5   languageCount    99951 non-null  int64
 6   description      97162 non-null  str
 7   primaryLanguage  91735 non-null  str
 8   createdAt        99951 non-null  datetime64[us, UTC]
 9   pushedAt         99951 non-null  datetime64[us, UTC]
 10  languages        99951 non-null  str
 11  topics           99951 non-null  str
 12  isFork           99951 non-null  bool
 13  isArchived       99951 non-null  bool
 14  repo_age_days    99951 non-null  int64
dtypes: bool(2), datetime64[us, UTC](2), int64(5), str(6)
memory usage: 10.9 MB

In [ ]:
df.isna().any()

owner              False
name                True
stars              False
forks              False
watchers           False
languageCount      False
description         True
primaryLanguage     True
createdAt          False
pushedAt           False
languages          False
topics             False
isFork             False
isArchived         False
repo_age_days      False
dtype: bool

In [ ]:
df[df['name'].isna()]

,owner,name,stars,forks,watchers,languageCount,description,primaryLanguage,createdAt,pushedAt,languages,topics,isFork,isArchived,repo_age_days
18547,nodejs,NaN,3332,522,113,6,Native Abstractions for Node.js,C++,2013-07-20 11:12:03+00:00,2025-07-10 16:43:00+00:00,"['C++', 'JavaScript', 'C', 'Python', 'CMake', ...","['nodejs', 'node']",False,False,4373
22035,guregu,NaN,2007,246,22,1,reasonable handling of nullable values,Go,2014-08-28 15:10:56+00:00,2025-03-05 18:44:45+00:00,['Go'],"['go', 'sql', 'json']",False,False,3842

In [ ]:
df = df[df['name'].fillna('').str.strip() != '']

In [ ]:
df.isna().sum()

owner                 0
name                  0
stars                 0
forks                 0
watchers              0
languageCount         0
description        2790
primaryLanguage    8219
createdAt             0
pushedAt              0
languages             0
topics                0
isFork                0
isArchived            0
repo_age_days         0
dtype: int64

In [38]:
df[df.duplicated(subset=['owner', 'name'],keep=False)]

Empty DataFrame
Columns: [owner, name, stars, forks, watchers, languageCount, description, primaryLanguage, createdAt, pushedAt, languages, topics, isFork, isArchived, repo_age_days]
Index: []

In [37]:
df = df.drop_duplicates(subset=['owner', 'name'])

In [ ]:
def validate_name(repository):
    name = repository['name']
    if pd.isna(name):
        return False
    if not isinstance(name,str):
        return False
    if name.strip() == "":
        return False
    return True

In [ ]:
def validate_date(repository):
    createdAt = repository['createdAt']
    pushedAt = repository['pushedAt']

    if not isinstance(createdAt,date):
        return False
    if not isinstance(pushedAt,date):
        return False
    if repository['repo_age_days'] < 0:
        return False
    return True