In [7]:
import ijson
path = '../data/repo_metadata.json'
with open(path, "rb") as f:
    first_repo = next(ijson.items(f, "item"))

first_repo

{'owner': 'freeCodeCamp',
 'name': 'freeCodeCamp',
 'stars': 426893,
 'forks': 41377,
 'watchers': 8588,
 'isFork': False,
 'isArchived': False,
 'languages': [{'name': 'TypeScript', 'size': 2843131},
  {'name': 'JavaScript', 'size': 725345},
  {'name': 'CSS', 'size': 207745},
  {'name': 'Dockerfile', 'size': 4446},
  {'name': 'HTML', 'size': 1341},
  {'name': 'Shell', 'size': 940}],
 'languageCount': 6,
 'topics': [{'name': 'learn-to-code', 'stars': 480},
  {'name': 'nonprofits', 'stars': 44},
  {'name': 'programming', 'stars': 1849},
  {'name': 'nodejs', 'stars': 85145},
  {'name': 'react', 'stars': 106415},
  {'name': 'd3', 'stars': 76},
  {'name': 'careers', 'stars': 60},
  {'name': 'education', 'stars': 684},
  {'name': 'teachers', 'stars': 39},
  {'name': 'javascript', 'stars': 181110}],
 'topicCount': 16,
 'diskUsageKb': 512574,
 'pullRequests': 41267,
 'issues': 19849,
 'description': "freeCodeCamp.org's open-source codebase and curriculum. Learn math, programming, and computer science for free.",
 'primaryLanguage': 'TypeScript',
 'createdAt': '2014-12-24T17:49:19Z',
 'pushedAt': '2025-08-31T09:33:14Z',
 'defaultBranchCommitCount': 39026,
 'license': 'BSD 3-Clause "New" or "Revised" License',
 'assignableUserCount': 42,
 'codeOfConduct': 'Other',
 'forkingAllowed': True,
 'nameWithOwner': 'freeCodeCamp/freeCodeCamp',
 'parent': None}

In [8]:
first_repo.keys()

dict_keys(['owner', 'name', 'stars', 'forks', 'watchers', 'isFork', 'isArchived', 'languages', 'languageCount', 'topics', 'topicCount', 'diskUsageKb', 'pullRequests', 'issues', 'description', 'primaryLanguage', 'createdAt', 'pushedAt', 'defaultBranchCommitCount', 'license', 'assignableUserCount', 'codeOfConduct', 'forkingAllowed', 'nameWithOwner', 'parent'])

In [9]:
repo = {
    'owner' : first_repo['owner'],
    'name' : first_repo['name'],
    'stars' : first_repo['stars'],
    'forks' : first_repo['forks'],
    'watchers' : first_repo['watchers'],
    'languageCount' : first_repo['languageCount'],
    'description' : first_repo['description'],
    'primaryLanguage' : first_repo['primaryLanguage'],
    'createdAt' : first_repo['createdAt'],
    'pushedAt' : first_repo['pushedAt']
    }

In [23]:
def extract_languages(languages):
    result = []
    for language in languages:
        result.append(language['name'])
    return result

In [11]:
repo['languages'] = extract_languages(first_repo['languages'])

In [12]:
repo

{'owner': 'freeCodeCamp',
 'name': 'freeCodeCamp',
 'stars': 426893,
 'forks': 41377,
 'watchers': 8588,
 'languageCount': 6,
 'description': "freeCodeCamp.org's open-source codebase and curriculum. Learn math, programming, and computer science for free.",
 'primaryLanguage': 'TypeScript',
 'createdAt': '2014-12-24T17:49:19Z',
 'pushedAt': '2025-08-31T09:33:14Z',
 'languages': ['TypeScript',
  'JavaScript',
  'CSS',
  'Dockerfile',
  'HTML',
  'Shell']}

In [24]:
def extract_topic(topics):
    result = []
    for topic in topics:
        result.append(topic['name'])
    return result

In [14]:
repo

{'owner': 'freeCodeCamp',
 'name': 'freeCodeCamp',
 'stars': 426893,
 'forks': 41377,
 'watchers': 8588,
 'languageCount': 6,
 'description': "freeCodeCamp.org's open-source codebase and curriculum. Learn math, programming, and computer science for free.",
 'primaryLanguage': 'TypeScript',
 'createdAt': '2014-12-24T17:49:19Z',
 'pushedAt': '2025-08-31T09:33:14Z',
 'languages': ['TypeScript',
  'JavaScript',
  'CSS',
  'Dockerfile',
  'HTML',
  'Shell']}

In [15]:
repo['topics'] = extract_topic(first_repo['topics'])

In [21]:
import os
import csv

In [27]:
path = '../data/repo_metadata.json'

output_dir = '../data/processed'
os.makedirs(output_dir, exist_ok=True)

batch_size = 50000
batch = []
file_number = 1

fieldnames = [
    'owner',
    'name',
    'stars',
    'forks',
    'watchers',
    'languageCount',
    'description',
    'primaryLanguage',
    'createdAt',
    'pushedAt',
    'languages',
    'topics'
]

with open(path, 'rb') as f:
    repositories = ijson.items(f, 'item')

    for repo_data in repositories:

        repo = {
            'owner': repo_data.get('owner'),
            'name': repo_data.get('name'),
            'stars': repo_data.get('stars'),
            'forks': repo_data.get('forks'),
            'watchers': repo_data.get('watchers'),
            'languageCount': repo_data.get('languageCount'),
            'description': repo_data.get('description'),
            'primaryLanguage': repo_data.get('primaryLanguage'),
            'createdAt': repo_data.get('createdAt'),
            'pushedAt': repo_data.get('pushedAt'),
            'languages': extract_languages(
                repo_data.get('languages', [])
            ),
            'topics': extract_topic(
                repo_data.get('topics', [])
            )
        }

        batch.append(repo)

        if len(batch) == batch_size:

            output_path = os.path.join(
                output_dir,
                f'repositories_{file_number:03d}.csv'
            )

            with open(output_path, 'w', newline='', encoding='utf-8') as csv_file:
                writer = csv.DictWriter(
                    csv_file,
                    fieldnames=fieldnames
                )

                writer.writeheader()
                writer.writerows(batch)

            print(f'Created {output_path}')

            batch.clear()
            file_number += 1

    if batch:

        output_path = os.path.join(
            output_dir,
            f'repositories_{file_number:03d}.csv'
        )

        with open(output_path, 'w', newline='', encoding='utf-8') as csv_file:
            writer = csv.DictWriter(
                csv_file,
                fieldnames=fieldnames
            )

            writer.writeheader()
            writer.writerows(batch)

        print(f'Created {output_path}')

print('Finished!')

Created ../data/processed\repositories_001.csv
Created ../data/processed\repositories_002.csv
Created ../data/processed\repositories_003.csv
Created ../data/processed\repositories_004.csv
Created ../data/processed\repositories_005.csv
Created ../data/processed\repositories_006.csv
Created ../data/processed\repositories_007.csv
Created ../data/processed\repositories_008.csv
Created ../data/processed\repositories_009.csv
Created ../data/processed\repositories_010.csv
Created ../data/processed\repositories_011.csv
Created ../data/processed\repositories_012.csv
Created ../data/processed\repositories_013.csv
Created ../data/processed\repositories_014.csv
Created ../data/processed\repositories_015.csv
Created ../data/processed\repositories_016.csv
Created ../data/processed\repositories_017.csv
Created ../data/processed\repositories_018.csv
Created ../data/processed\repositories_019.csv
Created ../data/processed\repositories_020.csv
Created ../data/processed\repositories_021.csv
Created ../data/processed\repositories_022.csv
Created ../data/processed\repositories_023.csv
Created ../data/processed\repositories_024.csv
Created ../data/processed\repositories_025.csv
Created ../data/processed\repositories_026.csv
Created ../data/processed\repositories_027.csv
Created ../data/processed\repositories_028.csv
Created ../data/processed\repositories_029.csv
Created ../data/processed\repositories_030.csv
Created ../data/processed\repositories_031.csv
Created ../data/processed\repositories_032.csv
Created ../data/processed\repositories_033.csv
Created ../data/processed\repositories_034.csv
Created ../data/processed\repositories_035.csv
Created ../data/processed\repositories_036.csv
Created ../data/processed\repositories_037.csv
Created ../data/processed\repositories_038.csv
Created ../data/processed\repositories_039.csv
Created ../data/processed\repositories_040.csv
Created ../data/processed\repositories_041.csv
Created ../data/processed\repositories_042.csv
Created ../data/processed\repositories_043.csv
Created ../data/processed\repositories_044.csv
Created ../data/processed\repositories_045.csv
Created ../data/processed\repositories_046.csv
Created ../data/processed\repositories_047.csv
Created ../data/processed\repositories_048.csv
Created ../data/processed\repositories_049.csv
Created ../data/processed\repositories_050.csv
Created ../data/processed\repositories_051.csv
Created ../data/processed\repositories_052.csv
Created ../data/processed\repositories_053.csv
Created ../data/processed\repositories_054.csv
Created ../data/processed\repositories_055.csv
Created ../data/processed\repositories_056.csv
Created ../data/processed\repositories_057.csv
Created ../data/processed\repositories_058.csv
Created ../data/processed\repositories_059.csv
Created ../data/processed\repositories_060.csv
Created ../data/processed\repositories_061.csv
Created ../data/processed\repositories_062.csv
Created ../data/processed\repositories_063.csv
Created ../data/processed\repositories_064.csv
Created ../data/processed\repositories_065.csv
Created ../data/processed\repositories_066.csv
Created ../data/processed\repositories_067.csv
Created ../data/processed\repositories_068.csv
Created ../data/processed\repositories_069.csv
Created ../data/processed\repositories_070.csv
Created ../data/processed\repositories_071.csv
Created ../data/processed\repositories_072.csv
Created ../data/processed\repositories_073.csv
Created ../data/processed\repositories_074.csv
Created ../data/processed\repositories_075.csv
Created ../data/processed\repositories_076.csv
Created ../data/processed\repositories_077.csv
Created ../data/processed\repositories_078.csv
Created ../data/processed\repositories_079.csv
Created ../data/processed\repositories_080.csv
Created ../data/processed\repositories_081.csv
Created ../data/processed\repositories_082.csv
Created ../data/processed\repositories_083.csv
Created ../data/processed\repositories_084.csv
Created ../data/processed\repositories_085.csv
Finished!

In [3]:
import pandas as pd

df = pd.read_csv('../data/processed/repositories_001.csv')
df.head()

,owner,name,stars,forks,watchers,languageCount,description,primaryLanguage,createdAt,pushedAt,languages,topics
0,freeCodeCamp,freeCodeCamp,426893,41377,8588,6,freeCodeCamp.org's open-source codebase and cu...,TypeScript,2014-12-24T17:49:19Z,2025-08-31T09:33:14Z,"['TypeScript', 'JavaScript', 'CSS', 'Dockerfil...","['learn-to-code', 'nonprofits', 'programming',..."
1,codecrafters-io,build-your-own-x,415801,38976,6247,1,Master programming by recreating your favorite...,Markdown,2018-05-09T12:03:18Z,2025-08-29T00:08:20Z,['Markdown'],"['programming', 'tutorials', 'tutorial-code', ..."
2,sindresorhus,awesome,396445,31414,8011,0,😎 Awesome lists about all kinds of interesting...,NaN,2014-07-11T13:42:37Z,2025-07-18T18:37:33Z,[],"['awesome', 'awesome-list', 'unicorns', 'lists..."
3,EbookFoundation,free-programming-books,366964,64025,9879,2,:books: Freely available programming books,Python,2013-10-11T06:50:37Z,2025-08-25T21:06:44Z,"['Python', 'HTML']","['education', 'books', 'list', 'resource', 'ha..."
4,public-apis,public-apis,363505,38166,4360,2,A collective list of free APIs,Python,2016-03-20T23:49:42Z,2025-05-20T15:56:34Z,"['Python', 'Shell']","['api', 'public-apis', 'free', 'apis', 'list',..."

In [7]:
df.shape

(50000, 12)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   owner            50000 non-null  str
 1   name             49998 non-null  str
 2   stars            50000 non-null  int64
 3   forks            50000 non-null  int64
 4   watchers         50000 non-null  int64
 5   languageCount    50000 non-null  int64
 6   description      48980 non-null  str
 7   primaryLanguage  45769 non-null  str
 8   createdAt        50000 non-null  str
 9   pushedAt         50000 non-null  str
 10  languages        50000 non-null  str
 11  topics           50000 non-null  str
dtypes: int64(4), str(8)
memory usage: 4.6 MB

In [10]:
(df['languages'] == '[]').sum()

np.int64(4241)

In [12]:
(df['topics'] == '[]').sum()

np.int64(16836)

In [13]:
((df['languages'] == '[]') & (df['topics'] == '[]')).sum()

np.int64(1800)

In [14]:
(
    df['description'].fillna('').str.strip().eq('')
    & df['languages'].eq('[]')
    & df['topics'].eq('[]')
).sum()

np.int64(152)

In [4]:
df[df['owner'].str.lower() == df['name'].str.lower()][
    ['owner', 'name', 'description', 'stars', 'languages', 'topics']
].head(20)

,owner,name,description,stars,languages,topics
0,freeCodeCamp,freeCodeCamp,freeCodeCamp.org's open-source codebase and cu...,426893,"['TypeScript', 'JavaScript', 'CSS', 'Dockerfil...","['learn-to-code', 'nonprofits', 'programming',..."
4,public-apis,public-apis,A collective list of free APIs,363505,"['Python', 'Shell']","['api', 'public-apis', 'free', 'apis', 'list',..."
10,awesome-selfhosted,awesome-selfhosted,A list of Free Software network services and w...,244591,[],"['selfhosted', 'awesome', 'awesome-list', 'pri..."
17,tensorflow,tensorflow,An Open Source Machine Learning Framework for ...,191404,"['C++', 'Python', 'MLIR', 'HTML', 'Starlark', ...","['tensorflow', 'machine-learning', 'python', '..."
22,ohmyzsh,ohmyzsh,"🙃 A delightful community-driven (with 2,400+...",181076,"['Shell', 'Python', 'Makefile']","['shell', 'zsh-configuration', 'theme', 'termi..."
26,flutter,flutter,Flutter makes it easy and fast to build beauti...,172214,"['Dart', 'C++', 'Java', 'Objective-C++', 'Obje...","['mobile', 'android', 'ios', 'material-design'..."
32,ollama,ollama,"Get up and running with OpenAI gpt-oss, DeepSe...",151319,"['Go', 'C', 'Shell', 'TypeScript', 'PowerShell...","['llama', 'llm', 'llama2', 'llms', 'go', 'gola..."
47,yt-dlp,yt-dlp,A feature-rich command-line audio/video downlo...,124809,"['Python', 'Makefile', 'Shell', 'Dockerfile', ...","['youtube-dl', 'python', 'sponsorblock', 'yt-d..."
50,electron,electron,:electron: Build cross-platform desktop apps w...,118112,"['C++', 'TypeScript', 'Objective-C++', 'JavaSc...","['electron', 'javascript', 'c-plus-plus', 'htm..."
51,kubernetes,kubernetes,Production-Grade Container Scheduling and Mana...,117187,"['Go', 'Shell', 'PowerShell', 'Makefile', 'Doc...","['kubernetes', 'go', 'cncf', 'containers']"
57,d3,d3,"Bring data to life with SVG, Canvas and HTML. ...",111384,"['Shell', 'JavaScript']","['visualization', 'data-visualization', 'chart..."
60,open-webui,open-webui,"User-friendly AI Interface (Supports Ollama, O...",108489,"['JavaScript', 'Svelte', 'Python', 'TypeScript...","['ollama', 'ollama-webui', 'llm', 'webui', 'se..."
62,axios,axios,Promise based HTTP client for the browser and ...,107514,"['JavaScript', 'TypeScript', 'HTML', 'Handleba...","['http-client', 'javascript', 'nodejs', 'promi..."
63,excalidraw,excalidraw,Virtual whiteboard for sketching hand-drawn li...,106257,"['TypeScript', 'SCSS', 'MDX', 'JavaScript', 'H...","['productivity', 'collaboration', 'diagrams', ..."
73,angular,angular,Deliver web apps with confidence 🚀,98586,"['TypeScript', 'JavaScript', 'Starlark', 'HTML...","['angular', 'typescript', 'web', 'javascript',..."
75,papers-we-love,papers-we-love,Papers from the computer science community to ...,97699,['Shell'],"['computer-science', 'read-papers', 'meetup', ..."
77,rustdesk,rustdesk,An open-source remote desktop application desi...,96833,"['Rust', 'Dart', 'C++', 'C', 'Kotlin', 'Python...","['remote-control', 'remote-desktop', 'teamview..."
82,ant-design,ant-design,An enterprise-class UI design language and Rea...,95857,"['TypeScript', 'JavaScript', 'CSS', 'Shell', '...","['react', 'ui-kit', 'typescript', 'antd', 'ant..."
87,pytorch,pytorch,Tensors and Dynamic neural networks in Python ...,92812,"['Python', 'C++', 'Cuda', 'C', 'Objective-C++'...","['neural-network', 'autograd', 'gpu', 'numpy',..."
89,neovim,neovim,Vim-fork focused on extensibility and usability,92410,"['Vim Script', 'Lua', 'C', 'CMake', 'Python', ...","['neovim', 'c', 'vim', 'lua', 'nvim', 'text-ed..."

In [6]:
df['stars'].describe()

count     50000.000000
mean       4719.690480
std       10087.858219
min         876.000000
25%        1508.000000
50%        2261.000000
75%        4300.250000
max      426893.000000
Name: stars, dtype: float64

In [7]:
df['forks'].describe()

count     50000.000000
mean        794.642720
std        2651.423544
min           0.000000
25%         164.000000
50%         326.000000
75%         678.250000
max      243520.000000
Name: forks, dtype: float64

In [8]:
df['watchers'].describe()

count    50000.000000
mean       114.092100
std        248.282939
min          0.000000
25%         29.000000
50%         57.000000
75%        116.000000
max       9879.000000
Name: watchers, dtype: float64

In [14]:
profile_repos =df[df['owner'].str.lower() == df['name'].str.lower()]

In [15]:
profile_repos.shape

(3859, 12)

In [16]:
profile_repos.head()

,owner,name,stars,forks,watchers,languageCount,description,primaryLanguage,createdAt,pushedAt,languages,topics
0,freeCodeCamp,freeCodeCamp,426893,41377,8588,6,freeCodeCamp.org's open-source codebase and cu...,TypeScript,2014-12-24T17:49:19Z,2025-08-31T09:33:14Z,"['TypeScript', 'JavaScript', 'CSS', 'Dockerfil...","['learn-to-code', 'nonprofits', 'programming',..."
4,public-apis,public-apis,363505,38166,4360,2,A collective list of free APIs,Python,2016-03-20T23:49:42Z,2025-05-20T15:56:34Z,"['Python', 'Shell']","['api', 'public-apis', 'free', 'apis', 'list',..."
10,awesome-selfhosted,awesome-selfhosted,244591,11318,2945,0,A list of Free Software network services and w...,NaN,2015-06-01T02:33:17Z,2025-08-31T16:32:54Z,[],"['selfhosted', 'awesome', 'awesome-list', 'pri..."
17,tensorflow,tensorflow,191404,74810,7453,26,An Open Source Machine Learning Framework for ...,C++,2015-11-07T01:19:20Z,2025-09-01T01:24:17Z,"['C++', 'Python', 'MLIR', 'HTML', 'Starlark', ...","['tensorflow', 'machine-learning', 'python', '..."
22,ohmyzsh,ohmyzsh,181076,26186,2636,3,"🙃 A delightful community-driven (with 2,400+...",Shell,2009-08-28T18:15:37Z,2025-08-26T03:13:21Z,"['Shell', 'Python', 'Makefile']","['shell', 'zsh-configuration', 'theme', 'termi..."